### PR TITLE
Upgrade Embongo

### PR DESCRIPTION
**Pull request by sleitner**
changed embongo version and the embedded mongo version used for tests.

### CODE REVIEW

**Comment by marcesher** [comment]
@sleitner any idea what's up with the travis failure?

**Comment by sleitner** [comment]
@marcesher fixed. Misunderstood what the embongo version referred to. It is the mongodb version that embongo uses for integration tests. I changed that from 2.6.0 to 3.0.6 to match the mongodb in production.

**Comment by marcesher** [comment]
Excellent. Thanks, @sleitner !

**Comment by jonathanwcrane** [comment]
Nice.

**Pull request merged**
